In [3]:
import pandas as pd
import requests

## Download de número de equipes via requests

### Por municípios

In [4]:
# Fazendo o download do arquivo
url = 'http://tabnet.datasus.gov.br/csv/cnes_cnv_equipebr163447187_19_163_35.csv' # link disponível no "copia .csv" após consulta no tabnet
#NOTE: o link é específico dessa consulta, para novas consultas, mudar o link

response = requests.get(url)

# Decodificando o conteúdo para a codificação correta
content = response.content.decode('ISO-8859-1')  # Ajuste conforme necessário

# Salvando o arquivo corrigido
with open('data/raw/quantitativo_equipes_mun_2026.csv', 'w', encoding='utf-8') as f:
    f.write(content)

## Leitura dos dados

In [26]:
# Fazendo o download do arquivo

equipes = pd.read_csv('data/raw/quantitativo_equipes_mun_2026.csv', sep=";")

equipes

,Município,01 ESF - EQUIPE DE SAUDE DA FAMILIA,02 ESFSB_M1 - ESF COM SAUDE BUCAL - M I,03 ESFSB_M2 - ESF COM SAUDE BUCAL - M II,04 EACS - EQUIPE DE AGENTES COMUNITARIOS DE SAUDE,05 EPEN - EQUIPE DE AT. SAUDE SIST. PENITENCIARIO,06 NASF1 - NUCLEO DE APOIO A SAUDE DA FAMILIA-NASF MODALIDADE 1,07 NASF2 - NUCLEO DE APOIO A SAUDE DA FAMILIA-NASF MODALIDADE 2,08 EMSI - EQ MULTIDISC AT BASICA SAUDE INDIGENA,10 EACSSB_M1 - EQ AGENTES COMUNITµRIOS COM SAUDE BUCAL - MI,...,53 EABP2SM - EQ ATENCAO BASICA PRISIONAL TIPO II C SAUDE MENTAL,54 EABP3 - EQ ATENCAO BASICA PRISIONAL TIPO III,70 ESF - EQUIPE DE SAUDE DA FAMILIA,71 ESB - EQUIPE DE SAUDE BUCAL,72 ENASF-AB - EQ NUCLEO AMPLIADO SAUDE DA FAMILIA AT. PRIMARIA,73 ECR - EQUIPE DOS CONSULTORIOS NA RUA,74 EABP - EQUIPE DE ATENCAO PRIMARIA PRISIONAL,75 EMAESM - EQ MULTIPROF ATENCAO ESPECIALIZADA SAUDE MENTAL,76 EAP - EQUIPE DE ATENCAO PRIMARIA,Total
0,110001 ALTA FLORESTA D'OESTE,-,-,-,-,-,-,-,1,-,...,-,-,8,1,1,-,1,-,-,12
1,110002 ARIQUEMES,-,-,-,-,-,-,-,-,-,...,-,-,25,4,-,-,-,-,-,31
2,110003 CABIXI,-,-,-,-,-,-,-,-,-,...,-,-,3,1,1,-,-,-,-,5
3,110004 CACOAL,-,-,-,-,-,-,-,4,-,...,-,-,24,14,2,-,1,-,-,45
4,110005 CEREJEIRAS,-,-,-,-,-,-,-,-,-,...,-,-,6,2,1,-,-,-,-,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,522200 VIANOPOLIS,-,-,-,-,-,-,-,-,-,...,-,-,5,5,1,-,-,-,-,11
5566,522205 VICENTINOPOLIS,-,-,-,-,-,-,-,-,-,...,-,-,4,4,1,-,-,-,-,9
5567,522220 VILA BOA,-,-,-,-,-,-,-,-,-,...,-,-,3,2,1,-,-,-,-,6
5568,522230 VILA PROPICIO,-,-,-,-,-,-,-,-,-,...,-,-,2,2,1,-,-,-,1,6
5569,530010 BRASILIA,2,-,-,-,-,-,-,-,-,...,-,-,650,341,61,9,28,8,-,1126

In [ ]:
equipes[['codigo_ibge', 'municipio']] = equipes['Município'].str.split(' ', expand=True, n=1)

equipes

,Município,01 ESF - EQUIPE DE SAUDE DA FAMILIA,02 ESFSB_M1 - ESF COM SAUDE BUCAL - M I,03 ESFSB_M2 - ESF COM SAUDE BUCAL - M II,04 EACS - EQUIPE DE AGENTES COMUNITARIOS DE SAUDE,05 EPEN - EQUIPE DE AT. SAUDE SIST. PENITENCIARIO,06 NASF1 - NUCLEO DE APOIO A SAUDE DA FAMILIA-NASF MODALIDADE 1,07 NASF2 - NUCLEO DE APOIO A SAUDE DA FAMILIA-NASF MODALIDADE 2,08 EMSI - EQ MULTIDISC AT BASICA SAUDE INDIGENA,10 EACSSB_M1 - EQ AGENTES COMUNITµRIOS COM SAUDE BUCAL - MI,...,70 ESF - EQUIPE DE SAUDE DA FAMILIA,71 ESB - EQUIPE DE SAUDE BUCAL,72 ENASF-AB - EQ NUCLEO AMPLIADO SAUDE DA FAMILIA AT. PRIMARIA,73 ECR - EQUIPE DOS CONSULTORIOS NA RUA,74 EABP - EQUIPE DE ATENCAO PRIMARIA PRISIONAL,75 EMAESM - EQ MULTIPROF ATENCAO ESPECIALIZADA SAUDE MENTAL,76 EAP - EQUIPE DE ATENCAO PRIMARIA,Total,codigo_ibge,municipio
0,110001 ALTA FLORESTA D'OESTE,-,-,-,-,-,-,-,1,-,...,8,1,1,-,1,-,-,12,110001,ALTA FLORESTA D'OESTE
1,110002 ARIQUEMES,-,-,-,-,-,-,-,-,-,...,25,4,-,-,-,-,-,31,110002,ARIQUEMES
2,110003 CABIXI,-,-,-,-,-,-,-,-,-,...,3,1,1,-,-,-,-,5,110003,CABIXI
3,110004 CACOAL,-,-,-,-,-,-,-,4,-,...,24,14,2,-,1,-,-,45,110004,CACOAL
4,110005 CEREJEIRAS,-,-,-,-,-,-,-,-,-,...,6,2,1,-,-,-,-,9,110005,CEREJEIRAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,522200 VIANOPOLIS,-,-,-,-,-,-,-,-,-,...,5,5,1,-,-,-,-,11,522200,VIANOPOLIS
5566,522205 VICENTINOPOLIS,-,-,-,-,-,-,-,-,-,...,4,4,1,-,-,-,-,9,522205,VICENTINOPOLIS
5567,522220 VILA BOA,-,-,-,-,-,-,-,-,-,...,3,2,1,-,-,-,-,6,522220,VILA BOA
5568,522230 VILA PROPICIO,-,-,-,-,-,-,-,-,-,...,2,2,1,-,-,-,1,6,522230,VILA PROPICIO
5569,530010 BRASILIA,2,-,-,-,-,-,-,-,-,...,650,341,61,9,28,8,-,1126,530010,BRASILIA

In [28]:
equipes.to_clipboard()

In [23]:
colunas_numericas = equipes.columns.difference(['codigo_ibge', 'municipio'])

equipes[colunas_numericas] = (
    equipes[colunas_numericas]
    .replace("-", '0')
    # .apply(pd.to_numeric, errors='coerce')
    # .astype(int)  # inteiro com suporte a NaN
)

equipes

,Município,01 ESF - EQUIPE DE SAUDE DA FAMILIA,02 ESFSB_M1 - ESF COM SAUDE BUCAL - M I,03 ESFSB_M2 - ESF COM SAUDE BUCAL - M II,04 EACS - EQUIPE DE AGENTES COMUNITARIOS DE SAUDE,05 EPEN - EQUIPE DE AT. SAUDE SIST. PENITENCIARIO,06 NASF1 - NUCLEO DE APOIO A SAUDE DA FAMILIA-NASF MODALIDADE 1,07 NASF2 - NUCLEO DE APOIO A SAUDE DA FAMILIA-NASF MODALIDADE 2,08 EMSI - EQ MULTIDISC AT BASICA SAUDE INDIGENA,10 EACSSB_M1 - EQ AGENTES COMUNITµRIOS COM SAUDE BUCAL - MI,...,70 ESF - EQUIPE DE SAUDE DA FAMILIA,71 ESB - EQUIPE DE SAUDE BUCAL,72 ENASF-AB - EQ NUCLEO AMPLIADO SAUDE DA FAMILIA AT. PRIMARIA,73 ECR - EQUIPE DOS CONSULTORIOS NA RUA,74 EABP - EQUIPE DE ATENCAO PRIMARIA PRISIONAL,75 EMAESM - EQ MULTIPROF ATENCAO ESPECIALIZADA SAUDE MENTAL,76 EAP - EQUIPE DE ATENCAO PRIMARIA,Total,codigo_ibge,municipio
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,8.0,1.0,1.0,NaN,1.0,NaN,NaN,12,110001,ALTA FLORESTA D'OESTE
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.0,4.0,NaN,NaN,NaN,NaN,NaN,31,110002,ARIQUEMES
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,1.0,1.0,NaN,NaN,NaN,NaN,5,110003,CABIXI
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,24.0,14.0,2.0,NaN,1.0,NaN,NaN,45,110004,CACOAL
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.0,2.0,1.0,NaN,NaN,NaN,NaN,9,110005,CEREJEIRAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,5.0,1.0,NaN,NaN,NaN,NaN,11,522200,VIANOPOLIS
5566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,4.0,1.0,NaN,NaN,NaN,NaN,9,522205,VICENTINOPOLIS
5567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,2.0,1.0,NaN,NaN,NaN,NaN,6,522220,VILA BOA
5568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2.0,1.0,NaN,NaN,NaN,1.0,6,522230,VILA PROPICIO
5569,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,650.0,341.0,61.0,9.0,28.0,8.0,NaN,1126,530010,BRASILIA

In [24]:
colunas_numericas

Index(['01 ESF - EQUIPE DE SAUDE DA FAMILIA',
       '02 ESFSB_M1 - ESF COM SAUDE BUCAL - M I',
       '03 ESFSB_M2 - ESF COM SAUDE BUCAL - M II',
       '04 EACS - EQUIPE DE AGENTES COMUNITARIOS DE SAUDE',
       '05 EPEN - EQUIPE DE AT. SAUDE SIST. PENITENCIARIO',
       '06 NASF1 - NUCLEO DE APOIO A SAUDE DA FAMILIA-NASF MODALIDADE 1',
       '07 NASF2 - NUCLEO DE APOIO A SAUDE DA FAMILIA-NASF MODALIDADE 2',
       '08 EMSI - EQ MULTIDISC AT BASICA SAUDE INDIGENA',
       '10 EACSSB_M1 - EQ AGENTES COMUNITµRIOS COM SAUDE BUCAL - MI',
       '16 EAB1 - EQUIPE DE ATENCAO BASICA TIPO I',
       '17 EAB2 - EQUIPE DE ATENCAO BASICA TIPO II',
       '18 EAB3 - EQUIPE DE ATENCAO BASICA TIPO III',
       '19 EAB1SB - EQUIPE DE ATENCAO BASICA TIPO I COM SAUDE BUCAL',
       '22 EMAD - EQUIPE MULTIDISCIPLINAR DE ATENCAO DOMICILIAR TIPO I',
       '23 EMAP - EQUIPE MULTIDISCIPLINAR DE APOIO',
       '24 ESF1      - ESTRATEGIA DE SAUDE DA FAMILIA TIPO I',
       '25 ESF1SB_M1 - ESF TIPO I COM SAUDE BUCAL MODALIDADE I',
       '33 ESF4      - ESTRATEGIA DE SAUDE DA FAMILIA TIPO IV',
       '34 ESF4SB_M1 - ESF TIPO IV COM SAUDE BUCAL MODALIDADE I',
       '36 ESFTRANS      - ESF TRANSITORIA',
       '37 ESFTRANSSB_M1 - ESF TRANSITORIA COM SAUDE BUCAL MI',
       '38 ESFTRANSSB_M2 - ESF TRANSITORIA COM SAUDE BUCAL MII',
       '40 eCR MI   - EQUIPE DOS CONSULTORIOS NA RUA MODALIDADE I',
       '41 eCR MII  - EQUIPE DOS CONSULTORIOS NA RUA MODALIDADE II',
       '42 eCR MIII - EQUIPE DOS CONSULTORIOS NA RUA MODALIDADE III',
       '43 ESB MI  - EQUIPE DE SAUDE BUCAL MODALIDADE I',
       '44 ESB MII - EQUIPE DE SAUDE BUCAL MODALIDADE II',
       '45 NASF3 - NUCLEO DE APOIO A SAUDE DA FAMILIA-NASF MODALIDADE 3',
       '46 EMAD - EQUIPE MULTIDISCIPLINAR DE ATENCAO DOMICILIAR TIPO II',
       '47 EAD - EQUIPE DE CUIDADOS DOMICILIARES',
       '50 EABP1   - EQ ATENCAO BASICA PRISIONAL TIPO I',
       '51 EABP1SM - EQ ATENCAO BASICA PRISIONAL TIPO I C SAUDE MENTAL',
       '52 EABP2   - EQ ATENCAO BASICA PRISIONAL TIPO II',
       '53 EABP2SM - EQ ATENCAO BASICA PRISIONAL TIPO II C SAUDE MENTAL',
       '54 EABP3   - EQ ATENCAO BASICA PRISIONAL TIPO III',
       '70 ESF - EQUIPE DE SAUDE DA FAMILIA', '71 ESB - EQUIPE DE SAUDE BUCAL',
       '72 ENASF-AB - EQ NUCLEO AMPLIADO SAUDE DA FAMILIA AT. PRIMARIA',
       '73 ECR - EQUIPE DOS CONSULTORIOS NA RUA',
       '74 EABP - EQUIPE DE ATENCAO PRIMARIA PRISIONAL',
       '75 EMAESM - EQ  MULTIPROF  ATENCAO ESPECIALIZADA SAUDE MENTAL',
       '76 EAP - EQUIPE DE ATENCAO PRIMARIA', 'Município', 'Total'],
      dtype='object')